### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by MLHRNTAPE-DEV** [ViscousPotential/GitSync#10]
Give ready binary or provide instructions on how to build it yourself.

**Comment by ViscousPot** [comment]
I will update the Readme with better instructions at some point.

For now, can you try 
- Cloning the repo
- Renaming the Secrets.template file to be Secrets.kt
- Create a Git Oauth app in the developer settings
- Copy the details into Secrets.kt
- Hit build

**Comment by ViscousPot** [comment]
I've now added better build instructions. Hope it's helpful :)

**Comment by ViscousPot** [comment]
Hi,

Not sure if you managed to resolve this, but I have released a newer version that is more stable. Please give it a go and let me know if you have any issues. Also I have added build instructions if you would like to try it out yourself

https://github.com/ViscousPotential/GitSync/releases/tag/v1.402


________________________________
From: mlithrnytape-devx3333 ***@***.***>
Sent: Monday, September 9, 2024 3:24:50 PM
To: ViscousPotential/GitSync ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ViscousPotential/GitSync] How to build it? (Issue #10)


Give ready binary or provide instructions on how to build it yourself.
