### ISSUE TITLE
Support 30+ repos

### ISSUE THREAD

**Issue by maxthoursie** [ViscousPotential/GitSync#14]
Great project, thanks!

I have too many repos, and I think it only fetches the first 30 (the default limit) from github. 

As a intermediate fix I tried to raise the limit to 100 with `.url("https://api.github.com/user/repos?per_page=100")` but I haven't been able to build the project yet. The proper solution would be to support paging I suppose.

**Comment by ViscousPot** [comment]
Hey sorry, I was away for some time. Latest release fixes this behaviour. 
Thanks for bringing it to my attention :)

https://github.com/ViscousPotential/GitSync/releases/tag/v1.402

I've also added a new section to the readme for build instructions. Let me know if you have any issues with them 🙏
