### ISSUE TITLE
Not Opening on my Smartphone

### ISSUE THREAD

**Issue by akashkennedy** [ViscousPotential/GitSync#7]
Hey you reddited me about your project so i checked it out and it does't runs on my mobile. it shows there was a problem parsing the package.

My low end device specs is this
Model: Oppo A12
Ram/Rom: 3/32GB
Chipset: Mediatek
Gpu: Adreno 
Android: 13

**Comment by ViscousPot** [comment]
Hi! That error often means that there was an issue with your download. Can you try again, making sure the download completes fully? Let me know if you still have problems

**Comment by ViscousPot** [comment]
Hey, did this work for you?

**Comment by akashkennedy** [comment]
Nah. It didn't work. It's because I'm using a Low End Phone I guess

**Comment by ViscousPot** [comment]
Hm.. The app will be on the Play Store soon hopefully, so maybe it will work then. The app should support Android 13 by default, but you're right, maybe the chipset is an issue.
I will close this for now, but watch out for a Play Store release!

**Comment by ViscousPot** [comment]
Hi!

I just came across something that might be useful here that I didn't check with you. Can you make sure you are following all the requirements outlined here?

https://stackoverflow.com/a/6329829

Maybe it was just one of those specifics that was preventing the install?

Hope it works!


________________________________
